require '../interpreter/all'
require '../interpreter/file_name'
require '../interpreter/bigger'
require '../interpreter/writable'
require '../interpreter/not'
require '../interpreter/or'
require '../interpreter/and'
